### ISSUE TITLE
Can't start golings using "golings"-Command

### ISSUE THREAD

**Issue by MasterStaz** [mauricioabreu/golings#11]
Hey there,

I just installed golings using "go install github.com/mauricioabreu/golings/golings@latest" and cloned the git, but I can't start golings with the command "golings watch", do to it not finding the command. I can start it using "go run golings/golings.go watch"

I suggest to update the README.md with this alternate method, if this problem occours to other users al well.

System Info:
go version: go1.20.5 linux/amd64
OS: Ubuntu 23.04 (lunar)

**Comment by mauricioabreu** [comment]
hey @MasterStaz thank you for taking time to open this issue.

What error did you get after running the `watch` command? Could you paste it here, please?
