### ISSUE TITLE
Switch Statement - Problem to solve the switch3 exercise

### ISSUE THREAD

**Issue by M200020947568** [mauricioabreu/golings#5]
In the third task, there is no hint in the switch statement to help the recipient get the idea of solving the task. As a result, I am unable to figure out how the task should be performed.

// switch3
// Make me compile!

// I AM NOT DONE
package main_test

import "testing"

func weekDay(day int) string {
	// Return the day of the week based on the
	// integer. Use a switch case to satisfy all test cases below
	return "Sunday"
}

func TestWeekDay(t *testing.T) {
	tests := []struct {
		input int
		want  string
	}{
		{input: 0, want: "Sunday"},
		{input: 1, want: "Monday"},
		{input: 2, want: "Tuesday"},
		{input: 3, want: "Wednesday"},
		{input: 4, want: "Thursday"},
		{input: 5, want: "Friday"},
		{input: 6, want: "Saturday"},
	}

	for _, tc := range tests {
		day := weekDay(tc.input)
		if day != tc.want {
			t.Errorf("expected %s but got %s", tc.want, day)
		}
	}
}

**Comment by mauricioabreu** [comment]
Thank you for opening an issue.

This exercise has no hints because it has tests. Also, the comment in the function code may guide you through solving the exercise. All the tests must pass.

**Comment by M200020947568** [comment]
Can you JUST show  hot to make this not everyone will be able to do this

**Comment by M200020947568** [comment]
Okay i made this exerecise but in the next time if you will be making another

**Comment by M200020947568** [comment]
I finish this exercise but in my opinion better would be if you put more hints in exercises
