### ISSUE TITLE
Not able to install and run golings

### ISSUE THREAD

**Issue by GGuinea** [mauricioabreu/golings#9]
## Describe the bug

Hi
I'm trying to make in working on my MacOS but I getting: 
```zsh: command not found: golings```

I've installed golings with command

```go install github.com/mauricioabreu/golings/golings@latest```

## To Reproduce

1. Just install golings
2. Try to execute any golings command

## Expected behavior

Golings working

## Environment

- OS: [e.g. linux, macos, windows]
- golings version (`golings --version` to check your installed version)
- go version (`go version` to check your installed version)

**Comment by GGuinea** [comment]
Hmm,
It's not directly.
'echo $GOBIN' returns /Users/<my_name>/go/bin
int the PATH i have following two:
/Users/<my_name>/go:/usr/local/go/bin

do you know what could be the problem?

**Comment by mauricioabreu** [comment]
Yes. Your $PATH should have the $GOBIN path to lookup for the golings program. If you are using zsh, you might want to update `~/.zshrc` file adding the $GOBIN path to $PATH. If you don't know how to do this, I can help you.

**Comment by GGuinea** [comment]
Yeah, it works.Thanks!
